# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20171016_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
