# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_country_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
