# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    # initial = True

    dependencies = [
        ('places', '0006_auto_20171115_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Indicators',
        ),
    ]
