# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='indicator',
        ),
        migrations.AddField(
            model_name='indicators',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.City'),
            preserve_default=False,
        ),
    ]
