# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='short_name',
        ),
    ]
