# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_country_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
