# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_country_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators_byDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=-1)),
                ('month', models.IntegerField(default=-1)),
                ('apparent_temp_high', models.FloatField(default=0)),
                ('apparent_temp_low', models.FloatField(default=0)),
                ('apparent_temp_max', models.FloatField(default=0)),
                ('apparent_temp_min', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('moonphase', models.FloatField(default=-1)),
                ('temp_max', models.FloatField(default=0)),
                ('temp_min', models.FloatField(default=0)),
                ('precip_intencity_max', models.FloatField(default=0)),
                ('precip_accumulation_max', models.FloatField(default=0)),
                ('precip_type', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField(default=0)),
                ('visibility', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Indicators_byMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('month_score', models.IntegerField(default=0)),
                ('wet_days_count', models.IntegerField(default=0)),
                ('average_apparent_temp', models.FloatField(default=0)),
                ('average_humidity', models.FloatField(default=0)),
                ('average_precipitation_intencity', models.FloatField(default=0)),
                ('average_precipitation_accumulation', models.FloatField(default=0)),
                ('count_of_rain_days', models.IntegerField(default=0)),
                ('count_of_snow_days', models.IntegerField(default=0)),
                ('count_of_sleet_days', models.IntegerField(default=0)),
                ('average_wind_speed', models.FloatField(default=0)),
                ('average_visibility', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='city',
        ),
        migrations.DeleteModel(
            name='Indicators',
        ),
    ]
