# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20180218_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators_byday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
