# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_indicators_byday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators_byday',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
