# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20180316_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators_byday',
            name='icon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='icon',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
