# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20180316_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators_bymonth',
            name='icon',
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='count_of_clear_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='count_of_cloudy_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='count_of_fog_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicators_bymonth',
            name='count_of_wind_days',
            field=models.IntegerField(default=0),
        ),
    ]
