# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20180318_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators_byday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='indicators_byday',
            name='month',
        ),
    ]
