# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20180422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators_byday',
            name='apparent_temp_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='apparent_temp_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='apparent_temp_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='apparent_temp_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='moonphase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='precip_accumulation_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='precip_intencity_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='precip_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='temp_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='temp_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='visibility',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_byday',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_apparent_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_precipitation_accumulation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_precipitation_intencity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_visibility',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='average_wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='pressure',
            field=models.FloatField(null=True),
        ),
    ]
