# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20180422_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators_byday',
            name='day_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicators_bymonth',
            name='month_score',
            field=models.IntegerField(default=0),
        ),
    ]
